### ISSUE TITLE
Uncaught TypeError: _.castArray is not a function

### ISSUE THREAD

**Issue by cemegginson** [yitzchak/linter-spell#1]
[Enter steps to reproduce below:]
1. Install linter-spell.
2. The error appears.

**Atom Version**: 1.8.0
**System**: linux 4.6.3-1-ARCH
**Thrown From**: [linter-spell](https://github.com/yitzchak/linter-spell) package, v0.2.1
### Stack Trace

Uncaught TypeError: _.castArray is not a function

```
At /home/casey/.atom/packages/linter-spell/lib/main.js:66

TypeError: _.castArray is not a function
    at Object.consumeGrammar (/home/casey/.atom/packages/linter-spell/lib/main.js:66:18)
    at Provider.module.exports.Provider.provide (/usr/share/atom/resources/app.asar/node_modules/service-hub/lib/provider.js:30:52)
    at /usr/share/atom/resources/app.asar/node_modules/service-hub/lib/service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
autocomplete-clang, v0.9.4
autocomplete-glsl, v0.2.3
linter, v1.11.14
linter-clang, v3.4.4
linter-cpplint, v1.0.1
linter-glsl, v2.0.5
linter-pylint, v1.2.0
linter-shellcheck, v1.2.0
linter-spell, v0.2.1
linter-spell-latex, v0.2.1
pdf-view, v0.50.0

# Dev
No dev packages
```

**Comment by yitzchak** [comment]
Try now please. Just pushed patch into v0.2.2

**Comment by cemegginson** [comment]
Thanks, that fixed it.
