### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by greencopper** [yitzchak/linter-spell#40]
```
TypeError: Cannot read property 'length' of undefined
    at TextBuffer.module.exports.TextBuffer.lineLengthForRow (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:494:29)
    at Spell.<anonymous> (/home/foo/.atom/packages/linter-spell/lib/spell.js:102:155)
    at undefined.next (native)
    at step (/home/foo/.atom/packages/linter-spell/lib/spell.js:13:273)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

This happens during ordinary text editing.

**Comment by yitzchak** [comment]
Are you still seeing this?

**Comment by Arcanemagus** [comment]
If this _is_ still happening, it looks like it would be triggered [here](https://github.com/yitzchak/linter-spell/blob/7f3b7e7ada378fbba059de64649b35528e7b953e/lib/spell.js#L102), which is only called in [two](https://github.com/yitzchak/linter-spell/blob/7f3b7e7ada378fbba059de64649b35528e7b953e/lib/dictionary-provider.js#L31) [places](https://github.com/yitzchak/linter-spell/blob/7f3b7e7ada378fbba059de64649b35528e7b953e/lib/dictionary-provider.js#L72), both of which seem to be using the range sent to them from the consumer of the `provideDictionary`, so I'm not sure there is much you could do other than checking for invalid points coming in from that.
