### ISSUE TITLE
Error 404 while trying to install linter-spell dependencies

### ISSUE THREAD

**Issue by audreytoskin** [yitzchak/linter-spell#44]
When I launch Atom with linter-spell enabled, I see a balloon saying it's trying to install some dependencies, then then this message:

> Failed to install linter-spell dependencies
These packages were not installed, check your console
for more info.
  • intentions

From the console:

```
[Package-Deps] Unable to install intentions , Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.2.1
gyp info using node@6.9.5 | linux | x64
gyp http GET https://atom.io/download/atom-shell/v5.10.0/node-v5.10.0-headers.tar.gz
gyp http 404 https://atom.io/download/atom-shell/v5.10.0/node-v5.10.0-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! install error 
gyp ERR! stack Error: 404 response downloading https://atom.io/download/atom-shell/v5.10.0/node-v5.10.0-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/usr/lib/node_modules/node-gyp/lib/install.js:244:14)
gyp ERR! stack     at emitOne (events.js:101:20)
gyp ERR! stack     at Request.emit (events.js:188:7)
gyp ERR! stack     at Request.onRequestResponse (/usr/lib/node_modules/request/request.js:951:10)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! stack     at ClientRequest.emit (events.js:188:7)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (_http_client.js:474:21)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:363:20)
gyp ERR! stack     at emitOne (events.js:96:13)
gyp ERR! System Linux 4.9.13-200.fc25.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/node-gyp/bin/node-gyp.js" "install" "--runtime=electron" "--target=5.10.0" "--dist-url=https://atom.io/download/atom-shell" "--arch=x64" "--ensure"
gyp ERR! cwd /home/terrycloth/.atom
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
```

**Comment by yitzchak** [comment]
Try doing a manual install of the `intentions` package.

**Comment by audreytoskin** [comment]
`apm install intentions` does seem to fix the issue. Was it a problem in `linter-spell`'s installation script, or was I having some kind of network issue?

**Comment by yitzchak** [comment]
It was probably a network problem. The dependency install is a little fragile, though. 

Glad you got it working!

**Comment by almereyda** [comment]
This error seems to be documented in

* https://github.com/atom/atom/issues/11080#issuecomment-193617920
* https://github.com/atom/apm/issues/322#issuecomment-206582713

with a workaround being to set the `ATOM_NODE_URL=https://gh-contractor-zcbenz.s3.amazonaws.com/atom-shell/dist` environment variable.

Please follow the links about details.
