### ISSUE TITLE
Failed to activate the linter-spell package

### ISSUE THREAD

**Issue by ChildishGiant** [yitzchak/linter-spell#57]
**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [linter-spell](https://github.com/AtomLinter/linter-spell) package 0.14.0

### Stack Trace

Failed to activate the linter-spell package

```
At Cannot find module 'lodash'

Error: Cannot find module 'lodash'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.18.0/resources/app/src/module-cache.js:354:58)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-spell/lib/main.js:7:15)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.18.0/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.18.0/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (~/AppData/Local/atom/app-1.18.0/resources/app/static/index.js:47:45)
    at require (internal/module.js:20:19)
    at customRequire (~/AppData/Local/atom/app-1.18.0/resources/app/static/<embedded>:96:26)
    at Package.module.exports.Package.requireMainModule (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:887:35)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:242:22)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:99:21)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.18.0/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:645:40)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:626:35
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.18.0/resources/app/src/config.js:346:24)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:621:25)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.18.0/resources/app/src/package-manager.js:603:52)
    at ~/AppData/Local/atom/app-1.18.0/resources/app/src/atom-environment.js:846:34
```

### Commands

```
```

### Non-Core Packages

```
autoclose-html 0.23.0 
autocomplete-json 5.5.0 
browser-plus 0.0.97 
busy-signal 1.4.3 
color-picker 2.2.5 
intentions 1.1.2 
json-colorer 1.0.0 
linter 2.2.0 
linter-spell 0.14.0 
linter-ui-default 1.6.2 
markdown-folder 0.5.0 
markdown-writer 2.6.5 
omnisharp-atom 0.31.2 
pigments 0.39.1 
webbox-color 0.5.9 
Zen 0.18.0 
```

**Comment by Arcanemagus** [comment]
Please try re-installing the package, occasionally Atom's package manager fails to properly install all dependencies.

**Comment by trentks** [comment]
Same exact issue, have uninstalled and reinstalled numerous times to the same effect.
```
### Stack Trace:

TypeError: logger.setLevel is not a function
    at Object.<anonymous> (/home/trent/.atom/packages/linter-spell/node_modules/linter-spell-word-list/node_modules/natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js:26:8)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/home/trent/.atom/packages/linter-spell/node_modules/linter-spell-word-list/node_modules/natural/lib/natural/index.js:81:26)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.<anonymous> (/home/trent/.atom/packages/linter-spell-latex/node_modules/linter-spell-word-list/main.js:3:14)
    at Module._compile (/usr/lib/atom/src/native-compile-cache.js:87:30)
    at Object.value [as .js] (/usr/lib/atom/src/compile-cache.js:234:23)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/usr/lib/atom/src/native-compile-cache.js:47:27)
    at Object.provideDictionary (/home/trent/.atom/packages/linter-spell/lib/main.js:90:20)
    at Package.module.exports.Package.activateServices (/usr/lib/atom/src/package.js:441:69)
    at Package.module.exports.Package.activateNow (/usr/lib/atom/src/package.js:254:16)
    at /usr/lib/atom/src/package.js:223:32
    at Package.module.exports.Package.measure (/usr/lib/atom/src/package.js:97:15)
    at /usr/lib/atom/src/package.js:216:26
    at Package.module.exports.Package.activate (/usr/lib/atom/src/package.js:213:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/lib/atom/src/package-manager.js:635:34)
    at /usr/lib/atom/node_modules/settings-view/lib/package-manager.js:505:29
    at exit (/usr/lib/atom/node_modules/settings-view/lib/package-manager.js:114:16)
    at triggerExitCallback (/usr/lib/atom/src/buffered-process.js:322:11)
    at /usr/lib/atom/src/buffered-process.js:343:11
    at Socket.<anonymous> (/usr/lib/atom/src/buffered-process.js:204:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

**Comment by Arcanemagus** [comment]
@trentks If you were hitting the "same exact issue" then your stack trace would be identical 😛. Can you file a new issue with steps to reproduce what you are hitting there?

**Comment by neumannm** [comment]
I have the same error as @trentks , I have just opened issue #58 about it.

**Comment by juancarloscastillo** [comment]
Similar error here, Ubuntu 14.04, Atom 1.18.0:

logger.setLevel is not a function
Hide Stack Trace
TypeError: logger.setLevel is not a function
    at Object.<anonymous> (/home/juan/.atom/packages/linter-spell/node_modules/linter-spell-word-list/node_modules/natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js:26:8)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/juan/.atom/packages/linter-spell/node_modules/linter-spell-word-list/node_modules/natural/lib/natural/index.js:81:26)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.<anonymous> (/home/juan/.atom/packages/linter-spell/node_modules/linter-spell-word-list/main.js:3:14)
    at Module.get_Module._compile (/usr/share/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/usr/share/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (file:///usr/share/atom/resources/app/static/index.js:47:45)
    at require (/usr/share/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.provideDictionary (/home/juan/.atom/packages/linter-spell/lib/main.js:90:20)
    at Package.module.exports.Package.activateServices (/usr/share/atom/resources/app/src/package.js:443:75)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:256:22)
    at /usr/share/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:99:21)
    at /usr/share/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:645:40)
    at /usr/share/atom/resources/app/src/package-manager.js:377:25
    at /usr/share/atom/resources/app/src/config.js:644:26
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:25:20)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:141:34)
    at Config.module.exports.Config.emitChangeEvent (/usr/share/atom/resources/app/src/config.js:835:35)
    at Config.module.exports.Config.setRawValue (/usr/share/atom/resources/app/src/config.js:621:25)
    at Config.module.exports.Config.set (/usr/share/atom/resources/app/src/config.js:236:20)
    at Config.module.exports.Config.removeAtKeyPath (/usr/share/atom/resources/app/src/config.js:386:18)
    at Package.module.exports.Package.enable (/usr/share/atom/resources/app/src/package.js:84:32)
    at PackageManager.module.exports.PackageManager.enablePackage (/usr/share/atom/resources/app/src/package-manager.js:188:20)
    at HTMLButtonElement.enablementButtonClickHandler (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-card.js:361:31)

**Comment by rcrooks** [comment]
same issue. Steps to reproduce:
1. Go to Settings>Install
2. Try to install linter-spell

Stack trace:
TypeError: Class constructor Disposable cannot be invoked without 'new'
    at new DictionaryProvider (/Users/rcrooks/.atom/packages/linter-spell/lib/dictionary-provider.js:11:40)
    at Object.activate (/Users/rcrooks/.atom/packages/linter-spell/lib/main.js:31:33)
    at Package.activateNow (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/57603FE2-3FDF-46EA-A253-D456966FBA43/d/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:2948796)
    at measure (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/57603FE2-3FDF-46EA-A253-D456966FBA43/d/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:2948208)
    at Package.measure (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/57603FE2-3FDF-46EA-A253-D456966FBA43/d/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:2945839)
    at activationPromise.activationPromise.Promise (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/57603FE2-3FDF-46EA-A253-D456966FBA43/d/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:2948068)
    at new Promise (<anonymous>)
    at Package.activate (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/57603FE2-3FDF-46EA-A253-D456966FBA43/d/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:2948011)
    at PackageManager.activatePackage (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/57603FE2-3FDF-46EA-A253-D456966FBA43/d/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:378441)
    at /private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/57603FE2-3FDF-46EA-A253-D456966FBA43/d/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:911548
    at r (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/57603FE2-3FDF-46EA-A253-D456966FBA43/d/Atom Beta.app/Contents/Resources/app/static/<embedded>:11:906154)
    at o (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/57603FE2-3FDF-46EA-A253-D456966FBA43/d/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:1036941)
    at t.bufferStream (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/57603FE2-3FDF-46EA-A253-D456966FBA43/d/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:1037095)
    at Socket.e.on (/private/var/folders/m_/zp9plyps3dv8kgnzrx89161h0000gn/T/AppTranslocation/57603FE2-3FDF-46EA-A253-D456966FBA43/d/Atom Beta.app/Contents/Resources/app/static/<embedded>:14:1035697)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:554:12)
The error was thrown from the linter-spell package. This issue has already been reported.

**Comment by Aerijo** [comment]
@rcrooks That looks like a very different issue, and is thrown from Atom Beta.

https://github.com/atom/atom/issues/18157

**Comment by jacob-roth** [comment]
similar here: 

1. `install linter-spell`
2. receive below message

**Atom**: 1.42.0 x64
**Electron**: 4.2.7
**OS**: Mac OS X 10.15.2
**Thrown From**: [linter-spell](https://github.com/AtomLinter/linter-spell) package 0.15.0


### Stack Trace

Failed to activate the linter-spell package

```
At The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

Error: The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.
    at getGuestInstanceId (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:241:13)
    at HTMLElement.send (/Applications/Atom.app/Contents/Resources/electron.asar/renderer/web-view/web-view.js:272:77)
    at WebviewHandler.updateStyles (/packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:169:23)
    at WebviewHandler.disposables.add.atom.styles.onDidUpdateStyleElement (/packages/markdown-preview-plus/lib/markdown-preview-view/webview-handler.js:70:18)
    at Function.simpleDispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1211760)
    at Emitter.emit (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:1213201)
    at StyleManager.addStyleSheet (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:369575)
    at Package.activateStylesheets (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3212716)
    at Package.activateNow (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3211146)
    at measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3210790)
    at Package.measure (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3208400)
    at activationPromise.activationPromise.Promise (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3210650)
    at new Promise (<anonymous>)
    at Package.activate (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:3210593)
    at PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:382547)
    at /Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:939855
    at r (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:934461)
    at n (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125002)
    at e.bufferStream (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1125090)
    at Socket.e.on (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:14:1123758)
    at Socket.emit (events.js:187:15)
    at Pipe._handle.close (net.js:606:12)
```

### Commands

```
     -3:50.8.0 core:close (div.package-detail)
     -3:48.5.0 core:save (input.hidden-input)
  2x -3:41.4.0 spell-check:toggle (input.hidden-input)
     -3:23.6.0 autoflow:reflow-selection (input.hidden-input)
     -3:04.5.0 diagnostics:go-to-first-diagnostic (input.hidden-input)
  2x -1:50.4.0 core:close (input.hidden-input)
     -1:40.7.0 core:save (input.hidden-input)
     -1:37.6.0 settings-view:open (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.6.0 
atom-latex 0.8.11 
busy-signal 1.4.3 
compare-files 0.8.1 
git-time-machine 1.5.9 
indent-detective 0.1.1 
ink 0.7.9 
intentions 1.1.5 
julia-client 0.6.6 
language-fortran 2.1.6 
language-julia 0.13.0 
language-latex 1.2.0 
language-matlab 0.2.1 
language-ocaml 1.9.5 
language-r 0.4.2 
latex-completions 0.3.3 
linter 2.2.0 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.6.10 
local-history 4.3.1 
markdown-image-paste 2.5.2 
markdown-preview-plus 3.8.1 
multi-cursor 2.1.5 
ocaml-indent 0.6.1 
ocaml-merlin 0.14.4 
open-this 0.5.0 
remote-atom 1.3.12 
teletype 0.1.4 
tool-bar 1.1.0 
uber-juno 0.1.2 
```
