### ISSUE TITLE
Package activation fails

### ISSUE THREAD

**Issue by neumannm** [yitzchak/linter-spell#58]
I cannot activate the linter-spell package. I have already tried to uninstall and install again several times. I also deactivated the spell-check package beforehand.

Here's the stacktrace and other information:

**Atom**: 1.18.0 x64
**Electron**: 1.3.15
**OS**: Ubuntu 16.04.2
**Thrown From**: [linter-spell](https://github.com/AtomLinter/linter-spell) package 0.14.0

### Stack Trace

Failed to activate the linter-spell package

```
At logger.setLevel is not a function

TypeError: logger.setLevel is not a function
    at /packages/linter-spell/node_modules/linter-spell-word-list/node_modules/natural/lib/natural/brill_pos_tagger/lib/Brill_POS_Tagger.js:26:8)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (opt/atom/resources/app/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-spell/node_modules/linter-spell-word-list/node_modules/natural/lib/natural/index.js:81:26)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (opt/atom/resources/app/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at /packages/linter-spell/node_modules/linter-spell-word-list/main.js:3:14)
    at Module.get_Module._compile (/opt/atom/resources/app/src/native-compile-cache.js:106:36)
    at Object.value [as .js] (/opt/atom/resources/app/src/compile-cache.js:239:29)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (opt/atom/resources/app/static/index.js:47:45)
    at require (/opt/atom/resources/app/src/native-compile-cache.js:66:33)
    at Object.provideDictionary (/packages/linter-spell/lib/main.js:90:20)
    at Package.module.exports.Package.activateServices (/opt/atom/resources/app/src/package.js:443:75)
    at Package.module.exports.Package.activateNow (/opt/atom/resources/app/src/package.js:256:22)
    at /opt/atom/resources/app/src/package.js:225:38
    at Package.module.exports.Package.measure (/opt/atom/resources/app/src/package.js:99:21)
    at /opt/atom/resources/app/src/package.js:218:32
    at Package.module.exports.Package.activate (/opt/atom/resources/app/src/package.js:215:40)
    at PackageManager.module.exports.PackageManager.activatePackage (/opt/atom/resources/app/src/package-manager.js:645:40)
    at /opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:519:35
    at exit (/opt/atom/resources/app/node_modules/settings-view/lib/package-manager.js:128:22)
    at triggerExitCallback (/opt/atom/resources/app/src/buffered-process.js:338:17)
    at /opt/atom/resources/app/src/buffered-process.js:359:17
    at Socket.<anonymous> (/opt/atom/resources/app/src/buffered-process.js:220:15)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
     -2:10.5.0 intentions:highlight (input.hidden-input)
     -2:10.4.0 core:save (input.hidden-input)
     -2:08.8.0 intentions:highlight (input.hidden-input)
     -2:08.4.0 command-palette:toggle (input.hidden-input)
  4x -2:06.4.0 core:move-down (input.hidden-input)
     -2:03.3.0 core:confirm (input.hidden-input)
     -2:03.3.0 settings-view:uninstall-packages (input.hidden-input)
  2x -1:38.3.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
ansi-to-utf8 0.4.0 
asciidoc-preview 2.10.2 
busy-signal 1.4.3 
convert-file-encoding 0.1.0 
export-html 3.1.0 
git-time-machine 1.5.9 
grammar-live-reload 1.0.5 
intentions 1.1.2 
language-latex 1.0.0 
language-oxpath 0.2.0 
linter 2.2.0 
linter-chktex 1.3.1 
linter-coffeelint 1.2.1 
linter-javac 1.9.4 
linter-markdown 4.1.0 
linter-pylint 2.1.0 
linter-spell 0.14.0 
linter-ui-default 1.6.2 
node_modules undefined 
```

**Comment by yitzchak** [comment]
Thanks for reporting the issue!

@Arcanemagus looks like this is another issue in `natural`. They just removed the `log4js` code in the offending code so upgrading the dependency will probably fix the issue. They have moved the `webworker-threads` into optional dependencies so a missing python installation shouldn't break the install.

Not really an ideal solution since all we are using out of `natural` is the Jaro-Winkler algorithm. Perhaps we should switch to a more lightweight solution such as [jaro-winkler](https://www.npmjs.com/package/jaro-winkler)?

**Comment by yitzchak** [comment]
@neumannm @juancarloscastillo @trentks @harish123400 Please try upgrading to the most recent versions.

- linter-spell@v0.15.0
- linter-spell-html@v0.7.0
- linter-spell-javascript@v0.8.0
- linter-spell-latex@v0.10.0
- linter-spell-project@v0.2.0
- linter-spell-ruby@v0.4.0

**Comment by neumannm** [comment]
Seems to be working, thanks.

**Comment by yitzchak** [comment]
Great! Closing, will reopen if needed.

**Comment by Arcanemagus** [comment]
> Not really an ideal solution since all we are using out of `natural` is the Jaro-Winkler algorithm. Perhaps we should switch to a more lightweight solution such as [jaro-winkler](https://www.npmjs.com/package/jaro-winkler)?

Sounds like a good idea, I haven't had that much time to dedicate to this org recently so I didn't see this till just now!

**Comment by yitzchak** [comment]
@Arcanemagus No worries. Merged and it should be resolved. Also in `linter-spell-word-list`.
